// 初級問題 (40問)
export const beginnerQuestions = [
  {
    id: 1,
    category: "JavaScript初級",
    question: "変数を宣言するキーワードとして正しいものはどれですか?",
    options: ["let", "define", "int", "letvar"],
    correct: 0,
    explanation:
      "JavaScriptでは var / let / const を使って変数を宣言します。var は関数スコープを持ちます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Grammar_and_types",
  },
  {
    id: 2,
    category: "JavaScript初級",
    question: "再代入できない変数(定数)を宣言するキーワードはどれですか?",
    options: ["let", "static", "const", "final"],
    correct: 2,
    explanation: "const は再代入できない変数(定数)を宣言します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/const",
  },
  {
    id: 3,
    category: "JavaScript初級",
    question: "文字列を表すために使用する記号はどれですか?",
    options: ["hello", '"hello"', "String hello", "<hello>"],
    correct: 1,
    explanation:
      "JavaScriptの文字列はシングルクォートまたはダブルクォートで囲みます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String",
  },
  {
    id: 4,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst a = 'Apple' + 3 + 'Pen';\nconsole.log(a);",
    options: [
      "Apple3Pen",
      "AppleAppleApplePen",
      "NaN",
      "エラーになる"
    ],
    correct: 0,
    explanation: "JavaScriptでは、文字列と数値を '+' 演算子でつなぐと、数値が自動的に文字列に変換されて結合されます。そのため、'Apple' と 3 と 'Pen' がそのままつながった結果になります。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Addition",
  },
  {
    id: 5,
    category: "JavaScript初級",
    question: "配列を作成するために使用する記号はどれですか?",
    options: ["{}", "()", "[]", "<>"],
    correct: 2,
    explanation: "配列は [] を使って作成します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array",
  },
  {
    id: 6,
    category: "JavaScript初級",
    question: "オブジェクトを作成するために使用する記号はどれですか?",
    options: ["[]", "{}", "()", "object()"],
    correct: 1,
    explanation: "オブジェクトは {} を使って作成します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object",
  },
  {
    id: 7,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst a = [1, 2, 3, 4, 5];\nconsole.log(a.slice(1, 4));",
    options: ["[1, 2, 3, 4]", "[2, 3, 4]", "[2, 3, 4, 5]", "[1, 2, 3]"],
    correct: 1,
    explanation:
      "slice(開始インデックス, 終了インデックス) メソッドは、開始位置から終了位置の『直前』までの要素を取り出して新しい配列を返します。この場合、インデックス1（値:2）から4の直前（値:4）までが取り出されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/slice",
  },
  {
    id: 8,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nlet x = 10;\n\nif (x === 1) {\n  console.log('yes');\n} else if (x < 10) {\n  console.log('no');\n} else {\n  console.log('yes or yes');\n}",
    options: ["エラーになる", "yes or yes", "yes", "no"],
    correct: 1,
    explanation:
      "変数xの値は10です。最初のif条件(10 === 1)は偽、次のelse if条件(10 < 10)も偽（10未満ではない）となるため、最終的にelseブロック内の処理が実行されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/if...else",
  },
  {
    id: 9,
    category: "JavaScript初級",
    question: "開発時にデバッグ情報を出力するメソッドはどれですか?",
    options: ["print()", "echo()", "console.log()", "log.console()"],
    correct: 2,
    explanation: "console.log() はデバッグ出力に使われます。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/console/log",
  },
  {
    id: 10,
    category: "JavaScript初級",
    question: "条件によって処理を分岐させる基本的な構文はどれですか?",
    options: ["for", "forEach", "if", "while"],
    correct: 2,
    explanation: "if 文は条件に応じて処理を分岐します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/if...else",
  },
  {
    id: 11,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst words = ['pine', 'apple', 'pen'];\nfor (const word of words) {\n  console.log(word);\n}",
    options: [
      "pine\npine\npine",
      "pine\napple\npen",
      "['pine', 'apple', 'pen']\n(3回繰り返される)",
      "エラーになる",
    ],
    correct: 1,
    explanation:
      "JavaScriptの for...of 文は、配列の各要素を順番に取り出して変数（この場合はword）に代入します。console.logは実行のたびに改行して出力するため、各単語が順番に表示されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of",
  },
  {
    id: 12,
    category: "JavaScript初級",
    question: "値と型の両方を厳密に比較する演算子はどれですか?",
    options: ["==", "=", "===", "!=="],
    correct: 2,
    explanation: "=== は値と型の両方を比較します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Strict_equality",
  },
  {
    id: 13,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nfor (let count = 0; count < 3; count++) {\n  console.log(count);\n}",
    options: ["0\n1\n2\n3", "count 1\ncount 2\ncount 3", "0\n1\n2", "1\n2\n3"],
    correct: 2,
    explanation:
      "JavaScriptのforループでは、countが0から始まり、3未満（0, 1, 2）の間処理が繰り返されます。countが3になった時点で条件式 (count < 3) が偽になるため、ループは終了します。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for",
  },
  {
    id: 14,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nfunction job(arg) {\n  const answer = arg + 1;\n  console.log(answer);\n}\njob(1);",
    options: ["1", "2", "answer", "エラーになる"],
    correct: 1,
    explanation:
      "関数jobが引数1で呼び出されます。関数内部で1 + 1が計算され、変数answerに2が代入されます。最後にconsole.log(2)が実行されるため、結果は2となります。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions",
  },
  {
    id: 15,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nfor (let i = 0; i < 4; i++) {\n  if (i === 2) {\n    continue;\n  }\n  console.log(i);\n}",
    options: ["0\n1\n2\n3", "1\n2\n3\n4", "0\n1\n3", "1\n2\n4"],
    correct: 2,
    explanation:
      "continue文が実行されると、その回の残りの処理（console.log）をスキップして次のループ（iが3の回）へ進みます。そのため、2だけが出力されず、0, 1, 3が表示されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/continue",
  },
  {
    id: 16,
    category: "JavaScript初級",
    question: "配列の要素数を取得するプロパティはどれですか?",
    options: ["size", "count", "length", "total"],
    correct: 2,
    explanation: "length プロパティで配列の要素数を取得します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/length",
  },
  {
    id: 17,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nfunction job(arg) {\n  const answer = arg + 1;\n}\nconsole.log(job(1));",
    options: ["undefined", "2", "null", "エラーになる"],
    correct: 0,
    explanation:
      "関数内で計算は行われていますが、値を返すための 'return' 文がありません。JavaScriptでは値を返さない関数を呼び出すと、デフォルトで undefined が返されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions#%E6%88%BB%E3%82%8A%E5%80%A4",
  },
  {
    id: 18,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nfunction job(a, b = 2) {\n  return a + b;\n}\nconsole.log(job(1));",
    options: ["エラーになる", "3", "1, 2", "1"],
    correct: 1,
    explanation:
      "この関数では第2引数 b にデフォルト値 2 が設定されています。job(1) と呼び出した場合、aには1が代入され、bにはデフォルト値の2が使われるため、1 + 2 = 3 が返されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Default_parameters",
  },
  {
    id: 19,
    category: "JavaScript初級",
    question: "両方の条件が真の場合のみ真を返す論理演算子はどれですか?",
    options: ["||", "&&", "!", "&"],
    correct: 1,
    explanation: "&& は論理AND演算子です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_AND",
  },
  {
    id: 20,
    category: "JavaScript初級",
    question: "真偽値を扱うデータ型はどれですか?",
    options: ["Boolean", "Bool", "TrueFalse", "Logic"],
    correct: 0,
    explanation: "真偽値は Boolean 型です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
  },
  {
    id: 21,
    category: "JavaScript初級",
    question:
      "次のコードの出力は何ですか?\n\nlet arr = [1, 2, 3];\narr.push(4);\nconsole.log(arr);",
    options: ["[1,2,3]", "[1,2,3,4]", "[4,1,2,3]", "エラー"],
    correct: 1,
    explanation: "push() は配列の末尾に要素を追加します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/push",
  },
  {
    id: 22,
    category: "JavaScript初級",
    question:
      '次のコードの出力は何ですか?\n\nlet str = "hello";\nconsole.log(str.length);',
    options: ["4", "5", "6", "エラー"],
    correct: 1,
    explanation: "length プロパティで文字列の長さを取得できます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/String/length",
  },
  {
    id: 23,
    category: "JavaScript初級",
    question: "while文はどのような特徴を持ちますか?",
    options: [
      "必ず1回実行される",
      "条件がtrueの間繰り返す",
      "回数が固定されている",
      "配列専用の構文",
    ],
    correct: 1,
    explanation: "while 文は条件が true の間、処理を繰り返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/while",
  },
  {
    id: 24,
    category: "JavaScript初級",
    question:
      '次のコードの出力は何ですか?\n\nlet x = 2;\nswitch(x) {\n  case 1: console.log("a"); break;\n  case 2: console.log("b"); break;\n}',
    options: ['"a"', '"b"', "エラー", "何も出力されない"],
    correct: 1,
    explanation: 'x=2 なので case 2 が実行され、"b" が出力されます',
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/switch",
  },
  {
    id: 25,
    category: "JavaScript初級",
    question: "配列の最初の要素にアクセスするインデックスはどれですか?",
    options: ["1", "-1", "0", "null"],
    correct: 2,
    explanation: "JavaScriptの配列は0から始まるインデックスを持ちます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array",
  },
  {
    id: 26,
    category: "JavaScript初級",
    question: "定義した関数を実行する正しい方法はどれですか?(funcは関数名)",
    options: ["func", "call func", "func()", "run func"],
    correct: 2,
    explanation: "関数名の後に () を付けて呼び出します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions",
  },
  {
    id: 27,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst num = { one: 1, two: 2 };\nnum['three'] = 3;\nconsole.log(num['three']);",
    options: ["3", "three", "{ three: 3 }", "エラーになる"],
    correct: 0,
    explanation:
      "JavaScriptのオブジェクトでは、ブラケット記法（['key']）を使って新しいプロパティを追加したり、その値を参照したりできます。ここでは 'three' というキーに 3 を代入しているため、それを出力すると 3 が表示されます。",
    url: "https://developer.mozilla.org/ja/docs/Learn/JavaScript/Objects/Basics",
  },
  {
    id: 28,
    category: "JavaScript初級",
    question: "変数のデータ型を調べる演算子はどれですか?",
    options: ["typecheck", "datatype", "typeof", "instanceof"],
    correct: 2,
    explanation: "typeof は値のデータ型を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/typeof",
  },
  {
    id: 29,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しく出力される数字の組み合わせはどれか。\n\nlet i = 0;\nwhile (i < 5) {\n  i += 2;\n  if (i === 4) {\n    i++;\n  }\n  console.log(i);\n}",
    options: ["2, 4, 5", "2, 5", "0, 2, 4", "2, 5, 7"],
    correct: 1,
    explanation: "1回目: i=0で開始→i+=2で2に→出力は2。2回目: i=2で継続→i+=2で4に→if文の条件に一致しi++で5に→出力は5。3回目: i=5なので条件(i < 5)を満たさず終了。結果、2と5が出力されます。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/while",
  },
  {
    id: 30,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst items = ['A', 'B', 'C'];\nlet res = '';\nfor (const item of items) {\n  if (item === 'B') continue;\n  res += item;\n}\nconsole.log(res);",
    options: ["ABC", "AC", "B", "A"],
    correct: 1,
    explanation:
      "for...of 文で配列の要素を順に取り出します。item が 'B' のときに continue が実行されるため、その回の追加処理（res += item）がスキップされ、結果として 'AC' となります。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of",
  },
  {
    id: 31,
    category: "JavaScript初級",
    question: "いずれかの条件が真の場合に真を返す論理演算子はどれですか?",
    options: ["&&", "||", "!", "&"],
    correct: 1,
    explanation: "|| は論理OR演算子です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Logical_OR",
  },
  {
    id: 32,
    category: "JavaScript初級",
    question: "breakの役割として正しいものはどれですか?",
    options: [
      "関数を終了する",
      "ループや switch文を終了する",
      "処理を続ける",
      "条件を判定する",
    ],
    correct: 1,
    explanation: "break はループや switch 文を終了します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/break",
  },
  {
    id: 33,
    category: "JavaScript初級",
    question: "真を表す真偽値はどれですか?",
    options: ["1", '"true"', "true", "yes"],
    correct: 2,
    explanation: "true は Boolean 型の真を表します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
  },
  {
    id: 34,
    category: "JavaScript初級",
    question:
      "次のコードを実行した結果として、正しいものはどれか。\n\nconst arr = ['a', 'b'];\nfor (const x in arr) {\n  console.log(x);\n}",
    options: ["'a', 'b'", "0, 1", "1, 2", "エラーになる"],
    correct: 1,
    explanation: "for...in 文は、配列の要素（値）ではなく、その要素のインデックス（0, 1, 2...）を順番に取り出します。要素そのものを取り出したい場合は for...of 文を使用します。",
    url: "https://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...in",
  },
  {
    id: 35,
    category: "JavaScript初級",
    question: "配列の最後の要素を削除して返すメソッドはどれですか?",
    options: ["shift()", "remove()", "pop()", "delete()"],
    correct: 2,
    explanation: "pop() は配列の最後の要素を削除します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/pop",
  },
  {
    id: 36,
    category: "JavaScript初級",
    question: "関数に渡す値を何と呼びますか?",
    options: ["引数", "戻り値", "変数", "定数"],
    correct: 0,
    explanation: "関数に渡す値は引数(arguments)と呼ばれます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions",
  },
  {
    id: 37,
    category: "JavaScript初級",
    question: "do...while文の特徴はどれですか?",
    options: [
      "必ず0回実行",
      "最低1回は実行される",
      "配列専用",
      "無限ループ専用",
    ],
    correct: 1,
    explanation: "do...while は最低1回は処理が実行されます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/do...while",
  },
  {
    id: 38,
    category: "JavaScript初級",
    question:
      'オブジェクトのプロパティにアクセスする方法はどれですか?\n\nlet obj = {name: "Taro", age: 20};',
    options: ["obj->name", 'obj["name"]', "obj::name", "obj=>name"],
    correct: 1,
    explanation:
      'オブジェクトのプロパティにはブラケット記法 obj["key"] またはドット記法 obj.key を使ってアクセスします',
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Property_accessors",
  },
  {
    id: 39,
    category: "JavaScript初級",
    question:
      "より厳格なコードチェックを行うモードを有効にする宣言はどれですか?",
    options: ["use strict;", '"use strict";', "strict();", "#strict"],
    correct: 1,
    explanation:
      '"use strict"; により strict モードが有効になり、より安全なJavaScriptが実行されます',
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Strict_mode",
  },
  {
    id: 40,
    category: "JavaScript初級",
    question: "JavaScriptが最も一般的に実行される環境はどれですか?",
    options: ["サーバーのみ", "Webブラウザ", "データベース", "OSカーネル"],
    correct: 1,
    explanation:
      "JavaScriptは主にWebブラウザ上で実行されますが、Node.jsなどでサーバー上でも動作します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript",
  },
];

// 中級問題 (40問)

export const intermediateQuestions = [
  {
    id: 41,
    category: "JavaScript中級",
    question:
      "次のコードの出力は何ですか?\n\nlet x = 10;\nif (true) {\n  let x = 20;\n  console.log(x);\n}\nconsole.log(x);",
    options: ["10, 20", "20, 20", "20, 10", "10, 10"],
    correct: 2,
    explanation:
      "let はブロックスコープを持つため、内部の x は外側の x に影響しません。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/let",
  },
  {
    id: 42,
    category: "JavaScript中級",
    question:
      "次のコードの実行結果は何ですか?\n\nconst obj = {a: 1};\nobj.a = 2;\nconsole.log(obj.a);",
    options: ["1", "2", "エラー", "undefined"],
    correct: 1,
    explanation:
      "const は再代入を禁止するだけで、オブジェクトのプロパティの変更は可能です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/const",
  },
  {
    id: 43,
    category: "JavaScript中級",
    question:
      "アロー関数のthisの扱いについて正しいものはどれですか?\n\nconst f = () => console.log(this);",
    options: [
      "独自のthisを持つ",
      "外側のスコープのthisを継承する",
      "newで呼び出せる",
      "argumentsオブジェクトを持つ",
    ],
    correct: 1,
    explanation: "アロー関数は外側の this を継承し、独自の this は持ちません。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Arrow_functions",
  },
  {
    id: 44,
    category: "JavaScript中級",
    question: "次のうち関数式はどれですか?",
    options: [
      "function foo() {}",
      "const foo = function() {}",
      "if (true) {}",
      "for (let i=0; i<5; i++) {}",
    ],
    correct: 1,
    explanation: "関数式は変数に代入された関数です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Functions",
  },
  {
    id: 45,
    category: "JavaScript中級",
    question: "引数にデフォルト値を設定する正しい書き方はどれですか?",
    options: ["a = 1", "a := 1", "a == 1", "default a = 1"],
    correct: 0,
    explanation: "引数のデフォルト値は = を使って設定します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/Default_parameters",
  },
  {
    id: 46,
    category: "JavaScript中級",
    question:
      "配列のシャローコピーを作成する方法はどれですか?\n\nconst arr = [1, 2, 3];",
    options: [
      "const arr2 = arr",
      "const arr2 = [...arr]",
      "const arr2 = copy(arr)",
      "const arr2 = clone(arr)",
    ],
    correct: 1,
    explanation: "スプレッド構文で配列のコピーを作成できます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Spread_syntax",
  },
  {
    id: 47,
    category: "JavaScript中級",
    question:
      "次のコードの出力は何ですか?\n\nconst arr = [1, 2, 3];\nconst newArr = arr.map(x => x * 2);\nconsole.log(newArr);",
    options: ["[1, 2, 3]", "[2, 4, 6]", "[1, 4, 9]", "[3, 6, 9]"],
    correct: 1,
    explanation: "map() は各要素を変換した新しい配列を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/map",
  },
  {
    id: 48,
    category: "JavaScript中級",
    question: "条件に一致する要素だけを返す配列メソッドはどれですか?",
    options: ["map()", "reduce()", "filter()", "some()"],
    correct: 2,
    explanation: "filter() は条件に一致する要素だけを返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/filter",
  },
  {
    id: 49,
    category: "JavaScript中級",
    question: "配列を単一の値に集約するメソッドはどれですか?",
    options: ["map()", "filter()", "reduce()", "every()"],
    correct: 2,
    explanation: "reduce() は配列を単一の値に集約します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/reduce",
  },
  {
    id: 50,
    category: "JavaScript中級",
    question: "次のコードで真(truthy)と評価される値はどれですか?",
    options: ["0", '""', "null", "[]"],
    correct: 3,
    explanation: "空配列 [] は truthy な値です。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Truthy",
  },
  {
    id: 51,
    category: "JavaScript中級",
    question: "次のコードで偽(falsy)と評価される値はどれですか?",
    options: ['"false"', "[]", "{}", "null"],
    correct: 3,
    explanation: "null は falsy な値です。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Falsy",
  },
  {
    id: 52,
    category: "JavaScript中級",
    question:
      "オブジェクトのキーと値のペアを配列として取得するメソッドはどれですか?",
    options: [
      "Object.keys()",
      "Object.values()",
      "Object.entries()",
      "Object.pairs()",
    ],
    correct: 2,
    explanation: "Object.entries() は [key, value] の配列を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/entries",
  },
  {
    id: 53,
    category: "JavaScript中級",
    question:
      "オブジェクトにプロパティが存在するか確認する演算子はどれですか?\n\nconst obj = {a: 1};\nconsole.log('a' ??? obj);",
    options: ["exists", "has", "in", "of"],
    correct: 2,
    explanation: "in 演算子でプロパティの存在を判定できます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/in",
  },
  {
    id: 54,
    category: "JavaScript中級",
    question:
      "配列を分割代入する正しい構文はどれですか?\n\nconst arr = [10, 20];",
    options: [
      "const a = arr[0]",
      "const [a, b] = arr",
      "const {a, b} = arr",
      "const a <- arr",
    ],
    correct: 1,
    explanation: "配列は [] を使って分割代入します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment",
  },
  {
    id: 55,
    category: "JavaScript中級",
    question:
      "オブジェクトを分割代入する正しい構文はどれですか?\n\nconst obj = {a: 1, b: 2};",
    options: [
      "const [a, b] = obj",
      "const {a, b} = obj",
      "const a = obj[]",
      "const a <= obj",
    ],
    correct: 1,
    explanation: "オブジェクトの分割代入は {} を使用します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment",
  },
  {
    id: 56,
    category: "JavaScript中級",
    question:
      "プロパティが存在しない可能性がある場合に安全にアクセスする演算子はどれですか?",
    options: ["?.", "??", "::", "=>"],
    correct: 0,
    explanation: "?. は安全にプロパティへアクセスする演算子です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Optional_chaining",
  },
  {
    id: 57,
    category: "JavaScript中級",
    question:
      "nullまたはundefinedの場合のみデフォルト値を使用する演算子はどれですか?",
    options: ["||", "&&", "??", "?."],
    correct: 2,
    explanation: "?? は null または undefined の場合のみ右辺を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing",
  },
  {
    id: 58,
    category: "JavaScript中級",
    question: "厳格モードの主な目的はどれですか?",
    options: [
      "コードを高速化する",
      "古い構文を有効化する",
      "エラーを厳密に検出する",
      "非同期処理を簡単にする",
    ],
    correct: 2,
    explanation: "strict モードはエラーを厳密に検出します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Strict_mode",
  },
  {
    id: 59,
    category: "JavaScript中級",
    question: "定義と同時に実行される関数の正しい構文はどれですか?",
    options: [
      "function() {}",
      "(function() {})()",
      "function run() {}()",
      "run(function() {})",
    ],
    correct: 1,
    explanation: "IIFE は定義直後に実行される関数です。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/IIFE",
  },
  {
    id: 60,
    category: "JavaScript中級",
    question: "thisの値を指定して関数を即座に実行するメソッドはどれですか?",
    options: ["bind()", "apply()", "call()", "invoke()"],
    correct: 2,
    explanation: "call() は this を指定して即時実行します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/call",
  },
  {
    id: 61,
    category: "JavaScript中級",
    question: "bind()メソッドが返すものはどれですか?",
    options: [
      "実行結果",
      "thisを束縛した新しい関数",
      "undefinedを返す",
      "エラーを返す",
    ],
    correct: 1,
    explanation: "bind() は this を束縛した新しい関数を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/bind",
  },
  {
    id: 62,
    category: "JavaScript中級",
    question: "apply()とcall()の主な違いはどれですか?",
    options: ["戻り値", "thisの指定方法", "引数の渡し方", "非同期処理"],
    correct: 2,
    explanation: "apply() は引数を配列で渡します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Function/apply",
  },
  {
    id: 63,
    category: "JavaScript中級",
    question: "for...of文で反復処理できるものはどれですか?",
    options: ["通常のオブジェクト", "配列やMap", "関数", "数値"],
    correct: 1,
    explanation: "for...of は iterable なオブジェクトを反復します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...of",
  },
  {
    id: 64,
    category: "JavaScript中級",
    question: "for...in文で列挙されるものはどれですか?",
    options: ["値", "インデックス", "オブジェクトのキー", "型"],
    correct: 2,
    explanation: "for...in はオブジェクトのキーを列挙します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for...in",
  },
  {
    id: 65,
    category: "JavaScript中級",
    question:
      "次のコードで配列をコピーする方法はどれですか?\n\nconst arr = [1, 2, 3];",
    options: [
      "arr2 = arr",
      "arr2 = [...arr]",
      "arr2 = copy(arr)",
      "arr2 = clone(arr)",
    ],
    correct: 1,
    explanation: "スプレッド構文で配列をコピーできます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/Spread_syntax",
  },
  {
    id: 66,
    category: "JavaScript中級",
    question: "Object.assign()の主な用途はどれですか?",
    options: [
      "配列結合",
      "オブジェクトのコピー・マージ",
      "関数定義",
      "プロトタイプ作成",
    ],
    correct: 1,
    explanation: "Object.assign() はオブジェクトをコピーまたはマージします。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Object/assign",
  },
  {
    id: 67,
    category: "JavaScript中級",
    question: "シャローコピー(浅いコピー)の特徴として正しいものはどれですか?",
    options: [
      "完全に独立したコピー",
      "ネストしたオブジェクトは参照を共有する",
      "JSON専用",
      "再帰的にコピーする",
    ],
    correct: 1,
    explanation: "浅いコピーはネストしたオブジェクトの参照を共有します。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Shallow_copy",
  },
  {
    id: 68,
    category: "JavaScript中級",
    question: "JSON.stringify()の役割はどれですか?",
    options: [
      "JSON文字列を解析する",
      "オブジェクトをJSON文字列に変換する",
      "JSONを検証する",
      "JSONを圧縮する",
    ],
    correct: 1,
    explanation: "JSON.stringify() はオブジェクトを JSON 文字列に変換します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/stringify",
  },
  {
    id: 69,
    category: "JavaScript中級",
    question: "JSON.parse()の役割はどれですか?",
    options: [
      "オブジェクトを文字列化する",
      "JSONを圧縮する",
      "JSON文字列をオブジェクトに変換する",
      "JSONを検証する",
    ],
    correct: 2,
    explanation: "JSON.parse() は JSON 文字列をオブジェクトに変換します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/JSON/parse",
  },
  {
    id: 70,
    category: "JavaScript中級",
    question: "エラーが発生する可能性のある処理を扱う構文はどれですか?",
    options: ["if...else", "switch", "try...catch", "throwError"],
    correct: 2,
    explanation: "try...catch で例外処理を行います。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Control_flow_and_error_handling",
  },
  {
    id: 71,
    category: "JavaScript中級",
    question: "意図的にエラーを発生させるキーワードはどれですか?",
    options: ["error", "throw", "catch", "raise"],
    correct: 1,
    explanation: "throw は例外を発生させます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/throw",
  },
  {
    id: 72,
    category: "JavaScript中級",
    question: "可変長の引数を配列として受け取る構文はどれですか?",
    options: ["spread", "rest", "arguments", "collect"],
    correct: 1,
    explanation:
      "残余引数(rest parameters)は ... を使って複数の引数を配列として受け取ります。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/rest_parameters",
  },
  {
    id: 73,
    category: "JavaScript中級",
    question: "argumentsオブジェクトの特徴として正しいものはどれですか?",
    options: [
      "配列である",
      "アロー関数でも使える",
      "配列風オブジェクトである",
      "ES6で追加された",
    ],
    correct: 2,
    explanation:
      "arguments は配列ではなく配列風オブジェクトです。アロー関数では使用できません。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions/arguments",
  },
  {
    id: 74,
    category: "JavaScript中級",
    question: "Math.random()が返す値の範囲はどれですか?",
    options: ["0〜1(1含む)", "0以上1未満", "1〜10", "-1〜1"],
    correct: 1,
    explanation: "Math.random() は 0 以上 1 未満の値を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Math/random",
  },
  {
    id: 75,
    category: "JavaScript中級",
    question:
      "現在の日時を取得するオブジェクトを生成する正しい方法はどれですか?",
    options: ["Date()", "new Date()", "Date.create()", "Date.now()"],
    correct: 1,
    explanation: "new Date() で Date オブジェクトを生成します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Date/Date",
  },
  {
    id: 76,
    category: "JavaScript中級",
    question: "指定時間後に処理を実行するWeb APIはどれですか?",
    options: ["setTimeout()", "delay()", "wait()", "sleep()"],
    correct: 0,
    explanation: "setTimeout() は非同期で処理を遅延実行します。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/setTimeout",
  },
  {
    id: 77,
    category: "JavaScript中級",
    question: "コールバック関数とは何ですか?",
    options: [
      "自動実行される関数",
      "他の関数に引数として渡される関数",
      "戻り値専用の関数",
      "非同期専用の関数",
    ],
    correct: 1,
    explanation:
      "コールバック関数は他の関数に引数として渡され、必要なときに呼び出されます。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Callback_function",
  },
  {
    id: 78,
    category: "JavaScript中級",
    question: "配列の全要素が条件を満たすか判定するメソッドはどれですか?",
    options: ["some()", "every()", "filter()", "includes()"],
    correct: 1,
    explanation: "every() は配列の全要素が条件を満たすか判定します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/every",
  },
  {
    id: 79,
    category: "JavaScript中級",
    question: "配列に特定の要素が含まれているか確認するメソッドはどれですか?",
    options: ["has()", "contains()", "includes()", "exists()"],
    correct: 2,
    explanation: "includes() は配列に要素が含まれているかを判定します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Array/includes",
  },
  {
    id: 80,
    category: "JavaScript中級",
    question: "ES Modulesでモジュールを読み込むキーワードはどれですか?",
    options: ["require", "include", "import", "load"],
    correct: 2,
    explanation: "ES Modules では import を使ってモジュールを読み込みます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Modules",
  },
];

// 上級問題 (40問)
export const advancedQuestions = [
  {
    id: 81,
    category: "JavaScript上級",
    question:
      "次のコードの出力は何ですか?\n\nfunction outer() {\n  let count = 0;\n  return function() {\n    count++;\n    return count;\n  };\n}\nconst fn = outer();\nconsole.log(fn(), fn());",
    options: ["1, 1", "1, 2", "0, 0", "エラー"],
    correct: 1,
    explanation: "クロージャは関数が作成された時点のスコープを保持します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Closures",
  },
  {
    id: 82,
    category: "JavaScript上級",
    question: "プロトタイプチェーンの主な役割は何ですか?",
    options: [
      "非同期処理を管理する",
      "継承を実現する",
      "変数スコープを制御する",
      "イベントを登録する",
    ],
    correct: 1,
    explanation:
      "JavaScript はプロトタイプチェーンによりオブジェクト継承を実現します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Inheritance_and_the_prototype_chain",
  },
  {
    id: 83,
    category: "JavaScript上級",
    question: "Promiseの初期状態を表すものはどれですか?",
    options: ["pending", "running", "completed", "resolved"],
    correct: 0,
    explanation: "Promise の状態は pending / fulfilled / rejected の3つです。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise",
  },
  {
    id: 84,
    category: "JavaScript上級",
    question:
      "Promiseチェーンで次のthenに値を渡すために使用するキーワードはどれですか?",
    options: ["return", "throw", "resolve", "await"],
    correct: 0,
    explanation: "then 内で return した値は次の then に渡されます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise/then",
  },
  {
    id: 85,
    category: "JavaScript上級",
    question: "Promiseのエラーをキャッチするメソッドはどれですか?",
    options: ["error()", "fail()", "catch()", "reject()"],
    correct: 2,
    explanation: "catch() は Promise チェーンのエラーを処理します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Promise/catch",
  },
  {
    id: 86,
    category: "JavaScript上級",
    question: "async関数が常に返すものはどれですか?",
    options: ["通常の値", "Promise", "undefined", "コールバック"],
    correct: 1,
    explanation: "async 関数は常に Promise を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/async_function",
  },
  {
    id: 87,
    category: "JavaScript上級",
    question: "awaitキーワードを使用できる場所はどれですか?",
    options: [
      "どこでも使用可能",
      "通常の関数内",
      "async関数内のみ",
      "グローバルスコープ",
    ],
    correct: 2,
    explanation: "await は async 関数内でのみ使用できます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/await",
  },
  {
    id: 88,
    category: "JavaScript上級",
    question: "イベントループの主な役割は何ですか?",
    options: [
      "DOMを操作する",
      "非同期処理の実行順を管理する",
      "メモリを解放する",
      "関数を定義する",
    ],
    correct: 1,
    explanation: "イベントループはコールスタックとタスクキューを管理します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop",
  },
  {
    id: 89,
    category: "JavaScript上級",
    question: "コールスタックは何を管理しますか?",
    options: [
      "非同期タスクのキュー",
      "実行中の関数呼び出し",
      "イベントリスナー",
      "Promise専用の領域",
    ],
    correct: 1,
    explanation: "コールスタックは実行中の関数呼び出しを管理します。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Call_stack",
  },
  {
    id: 90,
    category: "JavaScript上級",
    question: "マイクロタスクに分類されるものはどれですか?",
    options: ["setTimeout", "Promise.then", "setInterval", "DOMイベント"],
    correct: 1,
    explanation: "Promise.then はマイクロタスクとして処理されます。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/HTML_DOM_API/Microtask_guide",
  },
  {
    id: 91,
    category: "JavaScript上級",
    question: "ガベージコレクションの主な役割は何ですか?",
    options: [
      "コードを圧縮する",
      "未使用メモリを自動的に解放する",
      "処理速度を制御する",
      "非同期処理を管理する",
    ],
    correct: 1,
    explanation: "不要になったオブジェクトは自動的に解放されます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Memory_management",
  },
  {
    id: 92,
    category: "JavaScript上級",
    question: "WeakMapの特徴として正しいものはどれですか?",
    options: [
      "キーにプリミティブ型を使える",
      "ガベージコレクションされない",
      "キーが弱参照である",
      "JSONに変換できる",
    ],
    correct: 2,
    explanation:
      "WeakMap のキーは弱参照なので、参照がなくなるとガベージコレクションされます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
  },
  {
    id: 93,
    category: "JavaScript上級",
    question: "ジェネレーター関数を定義する正しい構文はどれですか?",
    options: ["function*", "generator", "yield*", "async*"],
    correct: 0,
    explanation:
      "ジェネレーター関数は function* で定義し、yield で一時停止します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/function*",
  },
  {
    id: 94,
    category: "JavaScript上級",
    question: "yieldの主な役割は何ですか?",
    options: [
      "値を返して関数を終了する",
      "一時停止して値を返す",
      "例外を投げる",
      "非同期処理を開始する",
    ],
    correct: 1,
    explanation: "yield はジェネレーターの実行を一時停止し値を返します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/yield",
  },
  {
    id: 95,
    category: "JavaScript上級",
    question: "Symbolの主な用途は何ですか?",
    options: ["数値演算", "一意な識別子の生成", "配列操作", "非同期制御"],
    correct: 1,
    explanation: "Symbol は常に一意な識別子を生成します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
  },
  {
    id: 96,
    category: "JavaScript上級",
    question: "Reflect APIの主な用途は何ですか?",
    options: [
      "DOM操作",
      "低レベルのオブジェクト操作",
      "非同期制御",
      "イベント管理",
    ],
    correct: 1,
    explanation: "Reflect は低レベルのオブジェクト操作を提供します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
  },
  {
    id: 97,
    category: "JavaScript上級",
    question: "Proxyの主な役割は何ですか?",
    options: [
      "関数の高速化",
      "オブジェクト操作の横取り",
      "非同期処理の簡略化",
      "メモリ管理",
    ],
    correct: 1,
    explanation: "Proxy はオブジェクト操作を横取りして処理を追加できます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
  },
  {
    id: 98,
    category: "JavaScript上級",
    question: "ES Modulesのスコープとして正しいものはどれですか?",
    options: ["グローバル", "関数", "ブロック", "モジュール"],
    correct: 3,
    explanation: "ES Modules は独立したモジュールスコープを持ちます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Guide/Modules",
  },
  {
    id: 99,
    category: "JavaScript上級",
    question: "トップレベルawaitが使用できる環境はどれですか?",
    options: ["通常のスクリプト", "CommonJS", "ES Modules", "JSON"],
    correct: 2,
    explanation: "トップレベル await は ES Modules でのみ使用可能です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Operators/await",
  },
  {
    id: 100,
    category: "JavaScript上級",
    question: "JavaScriptでデッドロックが発生しにくい理由は何ですか?",
    options: [
      "マルチスレッドだから",
      "基本的にシングルスレッドで動作するから",
      "GCがあるから",
      "Promiseがあるから",
    ],
    correct: 1,
    explanation:
      "JavaScript は基本的にシングルスレッドで動作するためデッドロックが起きにくいです。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/EventLoop",
  },
  {
    id: 101,
    category: "JavaScript上級",
    question: "Web Workerの主な用途は何ですか?",
    options: ["DOM操作", "UI描画", "バックグラウンド処理", "イベント登録"],
    correct: 2,
    explanation: "Web Worker はメインスレッドとは別に処理を実行します。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/Web_Workers_API",
  },
  {
    id: 102,
    category: "JavaScript上級",
    question: "SharedArrayBufferの特徴は何ですか?",
    options: [
      "スレッド間で共有不可",
      "同期処理専用",
      "複数スレッド間でメモリを共有できる",
      "Promise専用",
    ],
    correct: 2,
    explanation: "SharedArrayBuffer は複数スレッドでメモリを共有可能です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/SharedArrayBuffer",
  },
  {
    id: 103,
    category: "JavaScript上級",
    question: "Atomics APIの主な用途は何ですか?",
    options: ["非同期制御", "DOM同期", "共有メモリの同期操作", "イベント処理"],
    correct: 2,
    explanation: "Atomics は SharedArrayBuffer の同期操作を提供します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/Atomics",
  },
  {
    id: 104,
    category: "JavaScript上級",
    question:
      "モジュールからデフォルトエクスポートを行うキーワードはどれですか?",
    options: ["export", "export default", "module.exports", "public"],
    correct: 1,
    explanation: "export default はデフォルトエクスポートを定義します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/export",
  },
  {
    id: 105,
    category: "JavaScript上級",
    question: "strictモードで禁止されているものはどれですか?",
    options: ["letの使用", "宣言なしの変数代入", "constの使用", "アロー関数"],
    correct: 1,
    explanation: "Strict モードでは暗黙的グローバル変数の使用が禁止されます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Strict_mode",
  },
  {
    id: 106,
    category: "JavaScript上級",
    question: "末尾再帰最適化(TCO)の主な効果は何ですか?",
    options: [
      "必ず有効化される",
      "再帰を禁止する",
      "スタック消費を抑える",
      "Promise専用",
    ],
    correct: 2,
    explanation:
      "末尾再帰最適化(TCO)は再帰呼び出し時のスタック消費を抑えます。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Functions",
  },
  {
    id: 107,
    category: "JavaScript上級",
    question: "eval()の主な問題点は何ですか?",
    options: ["高速すぎる", "セキュリティと性能の問題", "非同期専用", "型安全"],
    correct: 1,
    explanation:
      "eval() はセキュリティや性能上の問題があるため推奨されません。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Global_Objects/eval",
  },
  {
    id: 108,
    category: "JavaScript上級",
    question: "モンキーパッチとは何ですか?",
    options: [
      "非同期パターン",
      "既存オブジェクトの振る舞いを変更すること",
      "クラス継承",
      "イベント登録",
    ],
    correct: 1,
    explanation:
      "モンキーパッチは既存のオブジェクトや関数の振る舞いを変更することです。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Monkey_patch",
  },
  {
    id: 109,
    category: "JavaScript上級",
    question: "関数型プログラミングの重要な原則は何ですか?",
    options: [
      "状態を多用する",
      "副作用を避ける",
      "クラス中心",
      "thisに依存する",
    ],
    correct: 1,
    explanation: "関数型プログラミングでは副作用を避けます。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Functional_programming",
  },
  {
    id: 110,
    category: "JavaScript上級",
    question: "イミュータブルデータの主な利点は何ですか?",
    options: ["変更が容易", "状態管理が予測しやすい", "高速I/O", "メモリ削減"],
    correct: 1,
    explanation: "イミュータブルデータは状態管理を予測しやすくします。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Immutable",
  },
  {
    id: 111,
    category: "JavaScript上級",
    question: "純粋関数(Pure Function)の条件は何ですか?",
    options: [
      "副作用がある",
      "同じ入力で常に同じ出力を返す",
      "グローバル変数を使う",
      "thisに依存する",
    ],
    correct: 1,
    explanation:
      "Pure Function は同じ入力に対して常に同じ出力を返し、副作用を持ちません。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Pure_function",
  },
  {
    id: 112,
    category: "JavaScript上級",
    question: "カリー化(Currying)とは何ですか?",
    options: [
      "配列操作",
      "複数引数関数を単一引数関数の連鎖に変換すること",
      "非同期制御",
      "ループ最適化",
    ],
    correct: 1,
    explanation: "カリー化は複数引数関数を単一引数関数の連鎖に変換します。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Currying",
  },
  {
    id: 113,
    category: "JavaScript上級",
    question: "デコレーター関数の主な役割は何ですか?",
    options: ["DOM操作", "関数の振る舞いを拡張する", "非同期制御", "型定義"],
    correct: 1,
    explanation:
      "デコレーターは関数の振る舞いをラップして拡張することができます。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Decorator",
  },
  {
    id: 114,
    category: "JavaScript上級",
    question: "オブザーバーパターンの主な用途は何ですか?",
    options: ["継承", "状態変更の通知", "メモリ管理", "配列操作"],
    correct: 1,
    explanation: "オブザーバーパターンは状態変化を監視し、通知します。",
    url: "http://developer.mozilla.org/ja/docs/Glossary/Observer_pattern",
  },
  {
    id: 115,
    category: "JavaScript上級",
    question: "イベント駆動プログラミングの特徴は何ですか?",
    options: [
      "逐次実行",
      "イベント発生に応じて処理を実行する",
      "再帰専用",
      "同期限定",
    ],
    correct: 1,
    explanation:
      "イベント発生に応じて処理を実行するのがイベント駆動プログラミングです。",
    url: "http://developer.mozilla.org/ja/docs/Learn/JavaScript/Building_blocks/Events",
  },
  {
    id: 116,
    category: "JavaScript上級",
    question: "バックプレッシャー問題が発生する状況はどれですか?",
    options: [
      "同期処理",
      "大量データのストリーム処理で消費が生産に追いつかない時",
      "DOM操作",
      "単純ループ",
    ],
    correct: 1,
    explanation:
      "ストリーム処理では消費が生産に追いつかないとバックプレッシャー問題が起きます。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/Streams_API",
  },
  {
    id: 117,
    category: "JavaScript上級",
    question: "ReadableStreamの主な用途は何ですか?",
    options: [
      "書き込み専用",
      "データを順次読み取る",
      "双方向通信",
      "イベント管理",
    ],
    correct: 1,
    explanation: "ReadableStream はデータを順次読み取るためのストリームです。",
    url: "http://developer.mozilla.org/ja/docs/Web/API/ReadableStream",
  },
  {
    id: 118,
    category: "JavaScript上級",
    question: "非同期イテレーターを処理する正しい構文はどれですか?",
    options: ["for...of", "for...in", "for await...of", "while await"],
    correct: 2,
    explanation: "for await...of は非同期イテレーターを処理します。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Reference/Statements/for-await...of",
  },
  {
    id: 119,
    category: "JavaScript上級",
    question: "TC39の主な役割は何ですか?",
    options: ["ブラウザ開発", "ECMAScript仕様の策定", "Node.js管理", "MDN運営"],
    correct: 1,
    explanation: "TC39 は ECMAScript の標準仕様を策定する委員会です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Language_Resources",
  },
  {
    id: 120,
    category: "JavaScript上級",
    question: "ECMAScriptとJavaScriptの関係として正しいものはどれですか?",
    options: [
      "別の言語",
      "ECMAScriptはJavaScriptの標準仕様",
      "JavaScriptがECMAScriptを定義",
      "無関係",
    ],
    correct: 1,
    explanation: "ECMAScript は JavaScript の標準仕様です。",
    url: "http://developer.mozilla.org/ja/docs/Web/JavaScript/Language_Resources",
  },
];
